name: ci

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-331-cybersec-${{ hashFiles('go.sum') }}
          restore-keys: ${{ runner.os }}-331-cybersec-

      - name: Install dependencies
        run: |
          go mod tidy
          git diff --exit-code --name-only

      - name: Run linter
        run: |
          go fmt ./...
          git diff --exit-code --name-only

      - name: Compile binary
        run: go build main.go
